version: "3.9"

services:

  postgres-db:
    image: postgres
    container_name: 'postgres-db'
    environment:
      - POSTGRES_DB=selhozservis
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 7432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
